FROM node:22-alpine

WORKDIR /app

COPY ./package.json ./package.json 

COPY ./package-lock.json ./package-lock.json 

RUN npm install

COPY ./backend ./backend
COPY ./prisma ./prisma

RUN npx prisma generate

CMD [ "npm", "run", "dev-prisma" ]