name: Continuous Deployment (Prod) (Backend)
on: 
    push
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the code
              uses: actions/checkout@v3

            - name: Docker Login
              uses: docker/login-action@v2
              with:
                username: ${{ secrets.DOCKERHUBUSERNAME }}
                password: ${{ secrets.DOCKERHUBPASSWORD}}
            - name: Build and push to Docker Hub    
              uses: docker/build-push-action@v4
              with:
                context: .
                file: ./docker/Dockerfile.backend
                push: true
                tags: imssb22/arch-backend:${{ github.sha }}  