name: Continuous Deployment (Prod) (Frontend)
on: 
    push
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the code
              uses: actions/checkout@v3

            - name: Docker Login
              uses: docker/login-action@v2
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_PASSWORD}}
            - name: Build and push to Docker Hub    
              uses: docker/build-push-action@v4
              with:
                context: .
                file: ./docker/Dockerfile.frontend
                push: true
                tags: imssb22/arch-frontend:${{ github.sha }}  